services:
  pixano-inference:
    image: pixano-inference:test
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - "8000:8000"
    environment:
      - HF_HOME=/home/root/hf_home
      - REDIS_URL=:${REDIS_PASSWORD?Missing REDIS_PASSWORD env variable}@redis
      - UVICORN_PORT=8000
      - UVICORN_HOST=0.0.0.0
    volumes:
      - ./data/hf_models:/home/root/hf_home
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  redis:
    image: redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD?Missing REDIS_PASSWORD env variable}
    command: /bin/sh -c 'redis-server --appendonly yes --requirepass $${REDIS_PASSWORD}'
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    restart: "unless-stopped"
    


