# @Copyright: CEA-LIST/DIASI/SIALV/LVA (2023)
# @Author: CEA-LIST/DIASI/SIALV/LVA <pixano@cea.fr>
# @License: CECILL-C
#
# This software is a collaborative computer program whose purpose is to
# generate and explore labeled data for computer vision applications.
# This software is governed by the CeCILL-C license under French law and
# abiding by the rules of distribution of free software. You can use,
# modify and/ or redistribute the software under the terms of the CeCILL-C
# license as circulated by CEA, CNRS and INRIA at the following URL
#
# http://www.cecill.info

# This workflow will lint Python code with black
# For more information see: https://black.readthedocs.io/en/stable/integrations/github_actions.html

name: Lint Python code

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "develop"
      - "main"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lint Python code with black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./pixano"

      - name: Lint Jupyter notebooks with black
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "./notebooks"
          jupyter: true
